{% set name = "dm-acme" %}
{% set version = "0.2.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
    sha256: f8cd4db6eb2e579f743f18c431351c4407526f6d4fec95bec9dbc0664048fd20

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps
  noarch: python


requirements:
  host:
    - pip
    - python >=3.6
  run:
    - absl-py
    - dm-env
    - dm-tree
    - numpy
    - pillow
    - python >=3.6

test:
  imports:
    - acme
    - acme.adders
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/dm-acme
  summary: A Python library for Reinforcement Learning.
  license: Apache-2.0
  license_file: LICENSE
  dev_url: https://github.com/deepmind/acme

extra:
  recipe-maintainers:
    - bollwyvl
